name: Update Logos

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-logos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Run script to update logos
        run: |
          python update_logos.py

      - name: Commit and push changes
        run: |
          if git status --porcelain | grep -q graphics/logos; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add graphics/logos
            git commit -m "Update logos"
            git push https://x-access-token:${{ secrets.YML_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No logo updates found"
          fi
